#!/bin/bash

echo -n "Digite algo: "

read valor_digitado

if [ "$valor_digitado" -eq "3"];

then 
	echo "Você digitou o numero 3"

elif [ "$valor_digitado" -eq "4" ]; then
	echo "Você digitou o numero 4"

elif [ "$valor_digitado" -eq "5" ]; then
	echo "Você digitou o numero 5"

else
 	echo "Você não digitou nenhum número aceito"

fi

