#!/bin/bash

principal()
{
escolha=-1

while [ $escolha -ne 0 ];
do
echo "Escolha uma opcao"
echo "2 - fazer tabuada do 2";
echo "3 - fazer tabuada do 3";
echo "4 - fazer tabuada do 4";
echo "0 - Sair";

echo -n ": ";
read escolha;

if [ "$escolha" -eq "2" ];
then
gerarTabuada2

elif [ "$escolha" -eq "3" ];
then
gerarTabuada3

elif [ "$escolha" -eq "4" ];
then
gerarTabuada4

fi

done
}


gerarTabuada4()
{
for ((i=0; i<11; i++))
do
echo "$i*4=" `expr $i \* 4` 
done
}

gerarTabuada3()
{
for ((i=0; i<11; i++))
do
echo "$i*3=" `expr $i \* 3`
done
}

gerarTabuada2()
{
for i in {1..10}; do
echo "$i*2=" `expr $i \* 2`
done
}


principal

